name: sidescroller_dart
description: A web app for creating audio-only sidescroller games with 0 code.
# version: 1.0.0
homepage: https://chrisnorman7.github.io/sidescroller-maker/

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
#  path: ^1.6.0
  http:

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
